### ISSUE TITLE
AttributeError: 'Encoder' object has no attribute 'register_module'

### ISSUE THREAD

**Issue by quhaoooo** [MCG-NKU/AMT#3]
![image](https://user-images.githubusercontent.com/99603607/233818356-92b0eaf8-8456-4733-bc3e-49e92b632813.png)

**Comment by NK-CS-ZZL** [comment]
I think this problem is caused by the version of pytorch. The func `register_module` is an alias for `add_module`, which is implemented in the ver. 1.7.0. So if you are using pytorch under this version, the error occurs. 
As a simple solution, you could replace all `register_module` by `add_module`. However, we highly recommend to use the version of Pytorch in the `environment.yaml`. 
For more info, you can refer to [Issue60397](https://github.com/pytorch/pytorch/issues/60397) in Pytorch repo or the [official documentation](https://pytorch.org/docs/versions.html).

**Comment by quhaoooo** [comment]
thx~
